### ISSUE TITLE
incompatibility listed when installing extension

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#48]
```
(jupysql-plugin) eduardo@macbookair dev/jupysql-plugin (43-follow-ups-lower-priority %) » jupyter labextension list
JupyterLab v3.6.5
/Users/eduardo/miniconda3/envs/jupysql-plugin/share/jupyter/labextensions
        jupyterlab-jupytext v1.3.8+dev enabled OK (python, jupytext)
        jupysql-plugin v0.1.6 enabled  X
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled OK (python, jupyterlab_widgets)


"jupysql-plugin@0.1.6" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLabExtension        Package
>=17.0.1 <18.0.0>=18.2.0 <19.0.0 react
```

I'm getting this incompatibility message. the extension works fine but looks like something we should tackle.

**Comment by tonykploomber** [comment]
This is because we are using `jupyterlab 3.*`, which uses React 17.* version.

I fixed by downgrading some peer-dependencies package in package.json, we may close this issue when [the fix PR](https://github.com/ploomber/jupysql-plugin/pull/45) is merged

[related commit](https://github.com/ploomber/jupysql-plugin/pull/45/commits/da10931f06ab01fd529dce285352628ad8eaa254)
