### ISSUE TITLE
connector widget: form resets when switching db

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#71]
if I fill out the form for a new connection:

![image](https://github.com/ploomber/jupysql-plugin/assets/989250/51b44a10-6d4c-4e6a-9a18-480bc938ce72)

and then switch the db from the dropdown, the form resets. it'll be better if it'd kept the values. note that some forms contain different fields (eg duckdb and sqlite only contain alias and database), so we should only fill out the ones that match

**Comment by edublancas** [comment]
one important detail is the alias: if the dropdown is changed, we should only keep the alias if the user modified it. if it didn't, then we should change it for the default alias that corresponds to the selected db in the dropdown

**Comment by neelasha23** [comment]
Need some clarifications:
1. Is this applicable if user clicks the `Create` button or user types some fields and then selects some other DB (without clicking `Create`) and the expected behaviour is that the inputs should be retained?
2. The point that you mentioned about alias, is it not applicable for ports as well?
@edublancas
